### ISSUE TITLE
Add support for Micronaut 4.x

### ISSUE THREAD

**Issue by kristoisberg** [kokuwaio/micronaut-openapi-codegen#268]
Micronaut 4.0.0 introduced breaking changes, which have made this package incompatible with it. 

There are likely more things that need to be changed, but for example, the signature of the `register` method in `TimeTypeConverterRegistrar` needs to be change from `public void register(ConversionService<?> conversionService)` to `public void register(MutableConversionService conversionService)`.

**Comment by sschnabe** [comment]
Hi, i've already migrated this codegen to micronaut 4 on branch [4.x](https://github.com/kokuwaio/micronaut-openapi-codegen/tree/4.x). Release will take some time because i'll add additional features: records, sealed interfaces for inheritance and OpenApiCodegen 7.x (7.0.0-beta is already included in 4.x branch).

Next week i'll deploy snapshots to sonatype, release will be done in august.

**Comment by sschnabe** [comment]
Released. Please open bug tickets if anything is broken.
